bootstrap_project_id                  = ""
network_hostproject_id                = ""
network_serviceproject_id             = "" // <service(producer/consumer)-project-id>
organization_stage_administrator      = ["user:user-example@example.com"]
networking_stage_administrator        = ["user:user-example@example.com"]
security_stage_administrator          = ["user:user-example@example.com"]
producer_stage_administrator          = ["user:user-example@example.com"]
networking_manual_stage_administrator = ["user:user-example@example.com"]
consumer_stage_administrator          = ["user:user-example@example.com"]
